### PR TITLE
[ID-192] Fix images

### LINKED ISSUE #192: [BUG] Fix images
**Describe the bug**
releated to https://github.com/rokwire/illinois-app/issues/5686

### PR DESCRIPTION
**Pull request by stefanvit**
Describe the bug
releated to https://github.com/rokwire/illinois-app/issues/5686

**Resolves #192 
 
## Review Time Estimate
- [ ] Immediately
- [ ] Within a week
- [ ] When possible

## Type of changes
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by petyos — COMMENTED** [review]
Could you please provide what the problem was and how you fixed it?

**Comment by stefanvit** [comment]
> Could you please provide what the problem was and how you fixed it?
Webtools is no longer using the legacy large.png and thumb.png image endpoints for new events and now supports only a single 16:9 image at eventImage.png. Initially, we assumed that all PNG variants might be available, but the Webtools team confirmed that for new events the only reliable indicator is imageUploaded=true, and only the eventImage.png endpoint should be used.The main issue was that when the daily Webtools sync ran, the imageURL was not being set on the event object because of these outdated assumptions. Additionally, processing many events  caused 504 timeouts, which was fixed by adding request timeouts.

File: driven/image/adapter.go [hunk 1]
```diff
@@ -70,76 +71,105 @@ func (im Adapter) ProcessImage(item model.WebToolsEvent) (*model.ContentImagesUR
 	return &res, nil
 }
 
-// Why do you call this API two times??
```
Comment (petyos) [inline driven/image/adapter.go:73]: Has this covered as it has been removed?

File: driven/image/adapter.go [hunk 2]
```diff
@@ -70,76 +71,105 @@ func (im Adapter) ProcessImage(item model.WebToolsEvent) (*model.ContentImagesUR
...
+	img, _, err := image.Decode(resp.Body)
 	if err != nil {
-		return nil, err
+		log.Printf(
+			"[webtools-image] decode failed originatingCalendarId=%s eventId=%s err=%v",
+			item.OriginatingCalendarID,
+			item.EventID,
+			err,
+		)
+		return nil, nil // ✅ skip image, continue batch
```
Comment (petyos) [inline driven/image/adapter.go:151]: Do not put AI emoticons in the code

**Review by petyos — COMMENTED** [review]
Look at comments

File: driven/image/adapter.go (hunk 1 above)
Comment (stefanvit) [reply driven/image/adapter.go:73]: its covered, just the comment was there

File: driven/image/adapter.go (hunk 2 above)
Comment (stefanvit) [reply driven/image/adapter.go:151]: i will fix it tonight and deploy version with the fixes?
