### PR TITLE
[ID-85]Webtools fixes

### LINKED ISSUE #86: Webtools fixes
**Describe the bug**
1.1 Images are not being brought in from Webtools in the All Event feed or the event details panel (see "Health Misinformation on Social Media" for tomorrow at noon on Prod versus Dev)

1.3 Locations in the event details card of a Webtools event are not underlined and tappable to Google Maps (they are on Prod)

### PR DESCRIPTION
**Pull request by stefanvit**
## Description
1.1 Images are not being brought in from Webtools in the All Event feed or the event details panel (see "Health Misinformation on Social Media" for tomorrow at noon on Prod versus Dev)

**Resolves #86 

## Review Time Estimate
- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by stefanvit** [comment]
@petyos , please try it when you have a chance and tell me how to process to finish the task

File: core/logic_events.go [hunk 1]
```diff
@@ -247,6 +253,15 @@ func (e eventsLogic) processWebToolsEvents() {
...
 	}
+	var withimage []model.WebToolsEvent
+	for _, l := range allWebToolsEvents {
+		if l.LargeImageUploaded != "" {
+			withimage = append(withimage, l)
+		}
+		allWebToolsEvents = withimage
+	}
+
+	//fmt.Print(withimage)
```
Comment (petyos) [inline core/logic_events.go:264]: Do not leave commented code

File: core/logic_events.go [hunk 2]
```diff
@@ -668,6 +684,167 @@ func contactsToDef(items []model.ContactLegacy) []model.ContactLegacy {
 	return defs
 }
 
+func counstructImage(originatingCalendarID, dataSourceEventID, eventID string, prefixPath string) string {
```
Comment (petyos) [inline core/logic_events.go:687]: We have discussed that you have to make all images processing before to apply the transaction as currently it will fail for sure with time out. You have to prepare for example 1000 or 2000 images which emans 1000 and 2000 time to ask webtools and then to upload to content bb.

Also, it will be well done if you introduce Images driven adapter and move there all logic related with the images.

File: core/logic_events.go [hunk 3]
```diff
@@ -668,6 +684,167 @@ func contactsToDef(items []model.ContactLegacy) []model.ContactLegacy {
...
+		fmt.Println("Image uploaded successfully!")
+		webtoolImageURL = imageURL
+	}
+	return webtoolImageURL
+}
+
+// Function to upload image to another API along with additional data
+func uploadImage(imageData []byte, height int, width int, quality int, path, fileName string) (string, error) {
+	// URL to which the request will be sent
+	targetURL := "https://api-dev.rokwire.illinois.edu/content/bbs/image"
```
Comment (petyos) [inline core/logic_events.go:780]: What about of when this go to anther environemnt with another url?

File: core/logic_events.go [hunk 4]
```diff
@@ -668,6 +684,167 @@ func contactsToDef(items []model.ContactLegacy) []model.ContactLegacy {
...
+		}
+
+		fmt.Println("Image uploaded successfully!")
+		webtoolImageURL = imageURL
+	}
+	return webtoolImageURL
+}
+
+// Function to upload image to another API along with additional data
+func uploadImage(imageData []byte, height int, width int, quality int, path, fileName string) (string, error) {
```
Comment (petyos) [inline core/logic_events.go:778]: We have discussed to have download image function too.

**Review by petyos — CHANGES_REQUESTED** [review]
Please take into account the feedback. Thanks.
